-- Create a single table to hold all the NISHI index data
-- This structure closely mirrors the "Long" format of a CSV: Community | Domain | Indicator | Scores

create table nishi_data (
  id bigint generated by default as identity primary key,
  community text not null,
  domain text not null,
  indicator text not null,
  base_score numeric,     -- numeric allows decimal precision
  adjusted_score numeric,
  
  -- Optional: add a created_at timestamp
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) to secure the data
alter table nishi_data enable row level security;

-- Policy: Allow ANONYMOUS (public) read access
-- This is required so your dashboard can read data without users logging in.
create policy "Public can view nishi data"
on nishi_data for select
to anon
using ( true );

-- Policy: Allow Authenticated users (you) to insert/update/delete
-- This allows you to manage data from the Supabase Table Editor.
create policy "Enable all access for authenticated users"
on nishi_data for all
to authenticated
using ( true )
with check ( true );
